server:
  port: 9999
  shutdown: graceful
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    threads:
      io: 4
      worker: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

spring:
  application:
    name: bfs-gateway
  # shutdown graceful 优雅停止缓冲时间
  lifecycle:
    timeout-per-shutdown-phase: 10s

  ## ---------
#  cloud:
#    gateway:
#      enabled: true
#      default-filters:
#        - StripPrefix=1
#        - Retry=3
#      httpclient:
#        connect-timeout: 10000
#        response-timeout: 10000
#        pool:
#          max-connections: 10000
#          acquire-timeout: 10000
#
#      routes:
#        - id: bfs-demo2
#          uri: lb://bfs-demo2
#          predicates:
#            - Path=/bfs-demo2/demo2/**
#          filters:
#          #- PrefixPath=/api